version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  discovery-server:
    build:
      context: .
      dockerfile: ./backend/parking/discovery-server/Dockerfile
    ports:
      - 8761:8761
    depends_on:
      - postgres

  api-gateway:
    build:
      context: .
      dockerfile: ./backend/parking/api-gateway/Dockerfile
    ports:
      - 8089:8089
    depends_on:
      - discovery-server

  analytics:
    build:
      context: .
      dockerfile: ./backend/parking/analytics/Dockerfile
    depends_on:
      - discovery-server
      - broker

  booking:
    build:
      context: .
      dockerfile: ./backend/parking/booking/Dockerfile
    depends_on:
      - discovery-server
      - broker

  location:
    build:
      context: .
      dockerfile: ./backend/parking/location/Dockerfile
    depends_on:
      - discovery-server

  parking-management:
    build:
      context: .
      dockerfile: ./backend/parking/parking-management/Dockerfile
    depends_on:
      - discovery-server

  payment:
    build:
      context: .
      dockerfile: ./backend/parking/payment/Dockerfile
    depends_on:
      - discovery-server

  user-management:
    build:
      context: .
      dockerfile: ./backend/parking/user-management/Dockerfile
    depends_on:
      - discovery-server

  frontend:
    build: ./frontend/parking
    ports:
      - 8080:8080
    depends_on:
      - api-gateway

volumes:
  postgres_data:
